apiVersion: v1
kind: ConfigMap
#kind: Secret
metadata:
  name: {{ template "microapp.envconfigmap" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
  #  "helm.sh/hook": pre-install,pre-upgrade
  #  "helm.sh/hook-weight": "1"
  #  "helm.sh/hook-delete-policy": "before-hook-creation"
#type: Opaque
data: 
{{ .Files.Get .Values.files.envvalues | indent 2 }}

