apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "microapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.bluemix.net/client-max-body-size: "size=10m"
    ingress.bluemix.net/redirect-to-https: "True"
spec:
  tls:
  - secretName: {{ .Values.tls.secret }}
    hosts:
    - "{{ .Values.domain }}.microapp-cluster-628e7c924395176ab7114ae8af6ef0fe-0000.us-south.containers.appdomain.cloud"
  rules:
  - host: "{{ .Values.domain }}.microapp-cluster-628e7c924395176ab7114ae8af6ef0fe-0000.us-south.containers.appdomain.cloud"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "microapp.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}

